# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty


# Setup
title:               'Dataism'
tagline:             'some blog posts...'
description:         'some blog posts...'
url:                 'https://moritzkoerber.github.io/'
baseurl:             'https://moritzkoerber.github.io/'
paginate:            5

# About/contact
author:
  name:              Moritz Körber
  url:               
  email:             
  github:            github.com/moritzkoerber
  twitter:           \@moritzkoerber

# Custom vars
version:             1.0.0
gems:
    [jekyll-paginate]
