# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty


# Setup
title:               'some blog posts...'
tagline:             'some blog posts...'
description:         'some blog posts...'
url:                 
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Moritz Körber
  url:               
  email:
  twitter:          @moritzkoerber

# Custom vars
version:             1.0.0
gems:
    [jekyll-paginate]
